apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration-job
  annotations:
    argocd.argoproj.io/sync-wave: 2
spec:
  backoffLimit: 2
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migration
          image: busybox
          command:
            - "sh"
            - "-c"
            - "echo 'Running db check $DB_HOST...'; sleep 30; echo 'connected!'"
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db_config
                  key: db_host
