apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: default
data:
  APP_NAME: "demo-app"
  APP_ENV: "dev"
  LOG_LEVEL: "INFO"
  DB_HOST: "mysql.default.svc.cluster.local"
  DB_PORT: "3306"
